---
abstract: 'One Mojolicious app to rule them all'
author:
  - 'Jan Henning Thorsen <jhthorsen@cpan.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Toadfarm
no_index:
  directory:
    - t
    - inc
requires:
  File::Which: 1.00
  Mojolicious: 5.00
resources:
  bugtracker: https://github.com/jhthorsen/toadfarm/issues
  homepage: https://github.com/jhthorsen/toadfarm
  repository: https://github.com/jhthorsen/toadfarm.git
version: 0.45
