---
abstract: 'One Mojolicious app to rule them all'
author:
  - 'Jan Henning Thorsen <jhthorsen@cpan.org>'
build_requires:
  Test::More: 0.90
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Toadfarm
no_index:
  directory:
    - t
    - inc
requires:
  Mojolicious: 4.30
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Toadfarm
  homepage: https://metacpan.org/release/Toadfarm
  license: http://dev.perl.org/licenses/
  repository: https://github.com/jhthorsen/toadfarm
version: 0.1301
